# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
